### ISSUE TITLE
[초기 세팅] 클라이언트 초기 세팅

### ISSUE THREAD

**Issue by Unuuuuu** [Unuuuuu/liar-game#4]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 클라이언트 초기 세팅

### TODO
1. [ ] ESLint & Prettier 세팅
2. [ ] styled-components 세팅
3. [ ] global style 세팅
4. [ ] 필요한 패키지 설치
